In [2]:
import duckdb
import pandas as pd

%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

%sql duckdb://

In [3]:
dataset_path = '/home/augusto/Desktop/dmeyf2025/Data/'
dataset_file = 'competencia_01_curado.csv'

In [4]:
%%sql
create or replace table competencia_01_curado as
select
    *
from read_csv_auto("{{dataset_path + dataset_file}}")

Empty DataFrame
Columns: [Success]
Index: []

In [5]:
%%sql 
create or replace table bajas as
select * from competencia_01_curado where clase_ternaria != 'CONTINUA'

Empty DataFrame
Columns: [Success]
Index: []

In [25]:
%sqlcmd columns --table bajas

+--------------------------------------+---------+----------+---------+---------------+---------+
|                 name                 |   type  | nullable | default | autoincrement | comment |
+--------------------------------------+---------+----------+---------+---------------+---------+
|          numero_de_cliente           |  BIGINT |   True   |   None  |     False     |   None  |
|               foto_mes               |  BIGINT |   True   |   None  |     False     |   None  |
|            active_quarter            |  BIGINT |   True   |   None  |     False     |   None  |
|             cliente_vip              |  BIGINT |   True   |   None  |     False     |   None  |
|               internet               |  BIGINT |   True   |   None  |     False     |   None  |
|             cliente_edad             |  BIGINT |   True   |   None  |     False     |   None  |
|          cliente_antiguedad          |  BIGINT |   True   |   None  |     False     |   None  |
|            mrentabilidad             |  FLOAT  |   True   |   None  |     False     |   None  |
|         mrentabilidad_annual         |  FLOAT  |   True   |   None  |     False     |   None  |
|             mcomisiones              |  FLOAT  |   True   |   None  |     False     |   None  |
|           mactivos_margen            |  FLOAT  |   True   |   None  |     False     |   None  |
|           mpasivos_margen            |  FLOAT  |   True   |   None  |     False     |   None  |
|              cproductos              |  BIGINT |   True   |   None  |     False     |   None  |
|               tcuentas               |  BIGINT |   True   |   None  |     False     |   None  |
|          ccuenta_corriente           |  BIGINT |   True   |   None  |     False     |   None  |
|     mcuenta_corriente_adicional      |  FLOAT  |   True   |   None  |     False     |   None  |
|          mcuenta_corriente           |  FLOAT  |   True   |   None  |     False     |   None  |
|             ccaja_ahorro             |  BIGINT |   True   |   None  |     False     |   None  |
|             mcaja_ahorro             |  FLOAT  |   True   |   None  |     False     |   None  |
|        mcaja_ahorro_adicional        |  FLOAT  |   True   |   None  |     False     |   None  |
|         mcaja_ahorro_dolares         |  FLOAT  |   True   |   None  |     False     |   None  |
|       cdescubierto_preacordado       |  BIGINT |   True   |   None  |     False     |   None  |
|            mcuentas_saldo            |  FLOAT  |   True   |   None  |     False     |   None  |
|           ctarjeta_debito            |  BIGINT |   True   |   None  |     False     |   None  |
|    ctarjeta_debito_transacciones     |  BIGINT |   True   |   None  |     False     |   None  |
|            mautoservicio             |  FLOAT  |   True   |   None  |     False     |   None  |
|            ctarjeta_visa             |  BIGINT |   True   |   None  |     False     |   None  |
|     ctarjeta_visa_transacciones      |  BIGINT |   True   |   None  |     False     |   None  |
|        mtarjeta_visa_consumo         |  FLOAT  |   True   |   None  |     False     |   None  |
|           ctarjeta_master            |  BIGINT |   True   |   None  |     False     |   None  |
|    ctarjeta_master_transacciones     |  BIGINT |   True   |   None  |     False     |   None  |
|       mtarjeta_master_consumo        |  FLOAT  |   True   |   None  |     False     |   None  |
|        cprestamos_personales         |  BIGINT |   True   |   None  |     False     |   None  |
|        mprestamos_personales         |  FLOAT  |   True   |   None  |     False     |   None  |
|        cprestamos_prendarios         |  BIGINT |   True   |   None  |     False     |   None  |
|        mprestamos_prendarios         |  FLOAT  |   True   |   None  |     False     |   None  |
|       cprestamos_hipotecarios        |  BIGINT |   True   |   None  |     False     |   None  |
|       mprestamos_hipotecarios        |  FLOAT  |   True   |   None  |     False     |   None  |
|             cplazo_fijo              |  BIGINT |   True   |   None  |     False     |   None  |
|         mplazo_fijo_dolares          |  FLOAT  |   True   |   None  |     False     |   None  |
|          mplazo_fijo_pesos           |  FLOAT  |   True   |   None  |     False     |   None  |
|             cinversion1              |  BIGINT |   True   |   None  |     False     |   None  |
|          minversion1_pesos           |  FLOAT  |   True   |   None  |     False     |   None  |
|         minversion1_dolares          |  FLOAT  |   True   |   None  |     False     |   None  |
|             cinversion2              |  BIGINT |   True   |   None  |     False     |   None  |
|             minversion2              |  FLOAT  |   True   |   None  |     False     |   None  |
|             cseguro_vida             |  BIGINT |   True   |   None  |     False     |   None  |
|             cseguro_auto             |  BIGINT |   True   |   None  |     False     |   None  |
|           cseguro_vivienda           |  BIGINT |   True   |   None  |     False     |   None  |
|    cseguro_accidentes_personales     |  BIGINT |   True   |   None  |     False     |   None  |
|           ccaja_seguridad            |  BIGINT |   True   |   None  |     False     |   None  |
|             cpayroll_trx             |  BIGINT |   True   |   None  |     False     |   None  |
|               mpayroll               |  FLOAT  |   True   |   None  |     False     |   None  |
|              mpayroll2               |  FLOAT  |   True   |   None  |     False     |   None  |
|            cpayroll2_trx             |  BIGINT |   True   |   None  |     False     |   None  |
|     ccuenta_debitos_automaticos      |  BIGINT |   True   |   None  |     False     |   None  |
|     mcuenta_debitos_automaticos      |  FLOAT  |   True   |   None  |     False     |   None  |
|  ctarjeta_visa_debitos_automaticos   |  BIGINT |   True   |   None  |     False     |   None  |
|  mttarjeta_visa_debitos_automaticos  |  FLOAT  |   True   |   None  |     False     |   None  |
| ctarjeta_master_debitos_automaticos  |  BIGINT |   True   |   None  |     False     |   None  |
| mttarjeta_master_debitos_automaticos |  FLOAT  |   True   |   None  |     False     |   None  |
|           cpagodeservicios           |  BIGINT |   True   |   None  |     False     |   None  |
|           mpagodeservicios           |  FLOAT  |   True   |   None  |     False     |   None  |
|           cpagomiscuentas            |  BIGINT |   True   |   None  |     False     |   None  |
|           mpagomiscuentas            |  FLOAT  |   True   |   None  |     False     |   None  |
|     ccajeros_propios_descuentos      |  BIGINT |   True   |   None  |     False     |   None  |
|     mcajeros_propios_descuentos      |  FLOAT  |   True   |   None  |     False     |   None  |
|       ctarjeta_visa_descuentos       |  BIGINT |   True   |   None  |     False     |   None  |
|       mtarjeta_visa_descuentos       |  FLOAT  |   True   |   None  |     False     |   None  |
|      ctarjeta_master_descuentos      |  BIGINT |   True   |   None  |     False     |   None  |
|      mtarjeta_master_descuentos      |  FLOAT  |   True   |   None  |     False     |   None  |
|      ccomisiones_mantenimiento       |  BIGINT |   True   |   None  |     False     |   None  |
|      mcomisiones_mantenimiento       |  FLOAT  |   True   |   None  |     False     |   None  |
|          ccomisiones_otras           |  BIGINT |   True   |   None  |     False     |   None  |
|          mcomisiones_otras           |  FLOAT  |   True   |   None  |     False     |   None  |
|                cforex                |  BIGINT |   True   |   None  |     False     |   None  |
|              cforex_buy              |  BIGINT |   True   |   None  |     False     |   None  |
|              mforex_buy              |  FLOAT  |   True   |   None  |     False     |   None  |
|             cforex_sell              |  BIGINT |   True   |   None  |     False     |   None  |
|             mforex_sell              |  FLOAT  |   True   |   None  |     False     |   None  |
|      ctransferencias_recibidas       |  BIGINT |   True   |   None  |     False     |   None  |
|      mtransferencias_recibidas       |  FLOAT  |   True   |   None  |     False     |   None  |
|       ctransferencias_emitidas       |  BIGINT |   True   |   None  |     False     |   None  |
|       mtransferencias_emitidas       |  FLOAT  |   True   |   None  |     False     |   None  |
|       cextraccion_autoservicio       |  BIGINT |   True   |   None  |     False     |   None  |
|       mextraccion_autoservicio       |  FLOAT  |   True   |   None  |     False     |   None  |
|         ccheques_depositados         |  BIGINT |   True   |   None  |     False     |   None  |
|         mcheques_depositados         |  FLOAT  |   True   |   None  |     False     |   None  |
|          ccheques_emitidos           |  BIGINT |   True   |   None  |     False     |   None  |
|          mcheques_emitidos           |  FLOAT  |   True   |   None  |     False     |   None  |
|   ccheques_depositados_rechazados    |  BIGINT |   True   |   None  |     False     |   None  |
|   mcheques_depositados_rechazados    |  FLOAT  |   True   |   None  |     False     |   None  |
|     ccheques_emitidos_rechazados     |  BIGINT |   True   |   None  |     False     |   None  |
|     mcheques_emitidos_rechazados     |  FLOAT  |   True   |   None  |     False     |   None  |
|             tcallcenter              |  BIGINT |   True   |   None  |     False     |   None  |
|      ccallcenter_transacciones       |  BIGINT |   True   |   None  |     False     |   None  |
|             thomebanking             |  BIGINT |   True   |   None  |     False     |   None  |
|      chomebanking_transacciones      |  BIGINT |   True   |   None  |     False     |   None  |
|         ccajas_transacciones         |  BIGINT |   True   |   None  |     False     |   None  |
|           ccajas_consultas           |  BIGINT |   True   |   None  |     False     |   None  |
|           ccajas_depositos           |  BIGINT |   True   |   None  |     False     |   None  |
|         ccajas_extracciones          |  BIGINT |   True   |   None  |     False     |   None  |
|             ccajas_otras             |  BIGINT |   True   |   None  |     False     |   None  |
|               catm_trx               |  BIGINT |   True   |   None  |     False     |   None  |
|                 matm                 |  FLOAT  |   True   |   None  |     False     |   None  |
|            catm_trx_other            |  BIGINT |   True   |   None  |     False     |   None  |
|              matm_other              |  FLOAT  |   True   |   None  |     False     |   None  |
|             ctrx_quarter             |  BIGINT |   True   |   None  |     False     |   None  |
|             tmobile_app              |  BIGINT |   True   |   None  |     False     |   None  |
|           cmobile_app_trx            |  BIGINT |   True   |   None  |     False     |   None  |
|          Master_delinquency          |  BIGINT |   True   |   None  |     False     |   None  |
|            Master_status             |  BIGINT |   True   |   None  |     False     |   None  |
|     Master_mfinanciacion_limite      |  FLOAT  |   True   |   None  |     False     |   None  |
|         Master_Fvencimiento          |  BIGINT |   True   |   None  |     False     |   None  |
|          Master_Finiciomora          |  BIGINT |   True   |   None  |     False     |   None  |
|          Master_msaldototal          |  FLOAT  |   True   |   None  |     False     |   None  |
|          Master_msaldopesos          |  FLOAT  |   True   |   None  |     False     |   None  |
|         Master_msaldodolares         |  FLOAT  |   True   |   None  |     False     |   None  |
|        Master_mconsumospesos         |  FLOAT  |   True   |   None  |     False     |   None  |
|       Master_mconsumosdolares        |  FLOAT  |   True   |   None  |     False     |   None  |
|         Master_mlimitecompra         |  FLOAT  |   True   |   None  |     False     |   None  |
|        Master_madelantopesos         |  FLOAT  |   True   |   None  |     False     |   None  |
|       Master_madelantodolares        |  BIGINT |   True   |   None  |     False     |   None  |
|        Master_fultimo_cierre         |  BIGINT |   True   |   None  |     False     |   None  |
|            Master_mpagado            |  FLOAT  |   True   |   None  |     False     |   None  |
|          Master_mpagospesos          |  FLOAT  |   True   |   None  |     False     |   None  |
|         Master_mpagosdolares         |  FLOAT  |   True   |   None  |     False     |   None  |
|           Master_fechaalta           |  BIGINT |   True   |   None  |     False     |   None  |
|         Master_mconsumototal         |  FLOAT  |   True   |   None  |     False     |   None  |
|           Master_cconsumos           |  BIGINT |   True   |   None  |     False     |   None  |
|      Master_cadelantosefectivo       |  BIGINT |   True   |   None  |     False     |   None  |
|          Master_mpagominimo          |  FLOAT  |   True   |   None  |     False     |   None  |
|           Visa_delinquency           |  BIGINT |   True   |   None  |     False     |   None  |
|             Visa_status              |  BIGINT |   True   |   None  |     False     |   None  |
|      Visa_mfinanciacion_limite       |  FLOAT  |   True   |   None  |     False     |   None  |
|          Visa_Fvencimiento           |  BIGINT |   True   |   None  |     False     |   None  |
|           Visa_Finiciomora           |  BIGINT |   True   |   None  |     False     |   None  |
|           Visa_msaldototal           |  FLOAT  |   True   |   None  |     False     |   None  |
|           Visa_msaldopesos           |  FLOAT  |   True   |   None  |     False     |   None  |
|          Visa_msaldodolares          |  FLOAT  |   True   |   None  |     False     |   None  |
|         Visa_mconsumospesos          |  FLOAT  |   True   |   None  |     False     |   None  |
|        Visa_mconsumosdolares         |  FLOAT  |   True   |   None  |     False     |   None  |
|          Visa_mlimitecompra          |  FLOAT  |   True   |   None  |     False     |   None  |
|         Visa_madelantopesos          |  FLOAT  |   True   |   None  |     False     |   None  |
|        Visa_madelantodolares         |  FLOAT  |   True   |   None  |     False     |   None  |
|         Visa_fultimo_cierre          |  BIGINT |   True   |   None  |     False     |   None  |
|             Visa_mpagado             |  FLOAT  |   True   |   None  |     False     |   None  |
|           Visa_mpagospesos           |  FLOAT  |   True   |   None  |     False     |   None  |
|          Visa_mpagosdolares          |  FLOAT  |   True   |   None  |     False     |   None  |
|            Visa_fechaalta            |  BIGINT |   True   |   None  |     False     |   None  |
|          Visa_mconsumototal          |  FLOAT  |   True   |   None  |     False     |   None  |
|            Visa_cconsumos            |  BIGINT |   True   |   None  |     False     |   None  |
|       Visa_cadelantosefectivo        |  BIGINT |   True   |   None  |     False     |   None  |
|           Visa_mpagominimo           |  FLOAT  |   True   |   None  |     False     |   None  |
|            clase_ternaria            | VARCHAR |   True   |   None  |     False     |   None  |
|                target                |  BIGINT |   True   |   None  |     False     |   None  |
+--------------------------------------+---------+----------+---------+---------------+---------+

In [21]:
%%sql
    create or replace table perfilbaja as
    SELECT
    t1.numero_de_cliente,
    (t1.active_quarter - t2.active_quarter) AS diferencia_active_quarter,
    (t1.cliente_vip - t2.cliente_vip) AS diferencia_cliente_vip,
    (t1.internet - t2.internet) AS diferencia_internet,
    (t1.cliente_edad - t2.cliente_edad) AS diferencia_cliente_edad,
    (t1.cliente_antiguedad - t2.cliente_antiguedad) AS diferencia_cliente_antiguedad,
    (t1.mrentabilidad - t2.mrentabilidad) AS diferencia_mrentabilidad,
    (t1.mrentabilidad_annual - t2.mrentabilidad_annual) AS diferencia_mrentabilidad_annual,
    (t1.mcomisiones - t2.mcomisiones) AS diferencia_mcomisiones,
    (t1.mactivos_margen - t2.mactivos_margen) AS diferencia_mactivos_margen,
    (t1.mpasivos_margen - t2.mpasivos_margen) AS diferencia_mpasivos_margen,
    (t1.cproductos - t2.cproductos) AS diferencia_cproductos,
    (t1.tcuentas - t2.tcuentas) AS diferencia_tcuentas,
    (t1.ccuenta_corriente - t2.ccuenta_corriente) AS diferencia_ccuenta_corriente,
    (t1.mcuenta_corriente_adicional - t2.mcuenta_corriente_adicional) AS diferencia_mcuenta_corriente_adicional,
    (t1.mcuenta_corriente - t2.mcuenta_corriente) AS diferencia_mcuenta_corriente,
    (t1.ccaja_ahorro - t2.ccaja_ahorro) AS diferencia_ccaja_ahorro,
    (t1.mcaja_ahorro - t2.mcaja_ahorro) AS diferencia_mcaja_ahorro,
    (t1.mcaja_ahorro_adicional - t2.mcaja_ahorro_adicional) AS diferencia_mcaja_ahorro_adicional,
    (t1.mcaja_ahorro_dolares - t2.mcaja_ahorro_dolares) AS diferencia_mcaja_ahorro_dolares,
    (t1.cdescubierto_preacordado - t2.cdescubierto_preacordado) AS diferencia_cdescubierto_preacordado,
    (t1.mcuentas_saldo - t2.mcuentas_saldo) AS diferencia_mcuentas_saldo,
    (t1.ctarjeta_debito - t2.ctarjeta_debito) AS diferencia_ctarjeta_debito,
    (t1.ctarjeta_debito_transacciones - t2.ctarjeta_debito_transacciones) AS diferencia_ctarjeta_debito_transacciones,
    (t1.mautoservicio - t2.mautoservicio) AS diferencia_mautoservicio,
    (t1.ctarjeta_visa - t2.ctarjeta_visa) AS diferencia_ctarjeta_visa,
    (t1.ctarjeta_visa_transacciones - t2.ctarjeta_visa_transacciones) AS diferencia_ctarjeta_visa_transacciones,
    (t1.mtarjeta_visa_consumo - t2.mtarjeta_visa_consumo) AS diferencia_mtarjeta_visa_consumo,
    (t1.ctarjeta_master - t2.ctarjeta_master) AS diferencia_ctarjeta_master,
    (t1.ctarjeta_master_transacciones - t2.ctarjeta_master_transacciones) AS diferencia_ctarjeta_master_transacciones,
    (t1.mtarjeta_master_consumo - t2.mtarjeta_master_consumo) AS diferencia_mtarjeta_master_consumo,
    (t1.cprestamos_personales - t2.cprestamos_personales) AS diferencia_cprestamos_personales,
    (t1.mprestamos_personales - t2.mprestamos_personales) AS diferencia_mprestamos_personales,
    (t1.cprestamos_prendarios - t2.cprestamos_prendarios) AS diferencia_cprestamos_prendarios,
    (t1.mprestamos_prendarios - t2.mprestamos_prendarios) AS diferencia_mprestamos_prendarios,
    (t1.cprestamos_hipotecarios - t2.cprestamos_hipotecarios) AS diferencia_cprestamos_hipotecarios,
    (t1.mprestamos_hipotecarios - t2.mprestamos_hipotecarios) AS diferencia_mprestamos_hipotecarios,
    (t1.cplazo_fijo - t2.cplazo_fijo) AS diferencia_cplazo_fijo,
    (t1.mplazo_fijo_dolares - t2.mplazo_fijo_dolares) AS diferencia_mplazo_fijo_dolares,
    (t1.mplazo_fijo_pesos - t2.mplazo_fijo_pesos) AS diferencia_mplazo_fijo_pesos,
    (t1.cinversion1 - t2.cinversion1) AS diferencia_cinversion1,
    (t1.minversion1_pesos - t2.minversion1_pesos) AS diferencia_minversion1_pesos,
    (t1.minversion1_dolares - t2.minversion1_dolares) AS diferencia_minversion1_dolares,
    (t1.cinversion2 - t2.cinversion2) AS diferencia_cinversion2,
    (t1.minversion2 - t2.minversion2) AS diferencia_minversion2,
    (t1.cseguro_vida - t2.cseguro_vida) AS diferencia_cseguro_vida,
    (t1.cseguro_auto - t2.cseguro_auto) AS diferencia_cseguro_auto,
    (t1.cseguro_vivienda - t2.cseguro_vivienda) AS diferencia_cseguro_vivienda,
    (t1.cseguro_accidentes_personales - t2.cseguro_accidentes_personales) AS diferencia_cseguro_accidentes_personales,
    (t1.ccaja_seguridad - t2.ccaja_seguridad) AS diferencia_ccaja_seguridad,
    (t1.cpayroll_trx - t2.cpayroll_trx) AS diferencia_cpayroll_trx,
    (t1.mpayroll - t2.mpayroll) AS diferencia_mpayroll,
    (t1.mpayroll2 - t2.mpayroll2) AS diferencia_mpayroll2,
    (t1.cpayroll2_trx - t2.cpayroll2_trx) AS diferencia_cpayroll2_trx,
    (t1.ccuenta_debitos_automaticos - t2.ccuenta_debitos_automaticos) AS diferencia_ccuenta_debitos_automaticos,
    (t1.mcuenta_debitos_automaticos - t2.mcuenta_debitos_automaticos) AS diferencia_mcuenta_debitos_automaticos,
    (t1.ctarjeta_visa_debitos_automaticos - t2.ctarjeta_visa_debitos_automaticos) AS diferencia_ctarjeta_visa_debitos_automaticos,
    (t1.mttarjeta_visa_debitos_automaticos - t2.mttarjeta_visa_debitos_automaticos) AS diferencia_mttarjeta_visa_debitos_automaticos,
    (t1.ctarjeta_master_debitos_automaticos - t2.ctarjeta_master_debitos_automaticos) AS diferencia_ctarjeta_master_debitos_automaticos,
    (t1.mttarjeta_master_debitos_automaticos - t2.mttarjeta_master_debitos_automaticos) AS diferencia_mttarjeta_master_debitos_automaticos,
    (t1.cpagodeservicios - t2.cpagodeservicios) AS diferencia_cpagodeservicios,
    (t1.mpagodeservicios - t2.mpagodeservicios) AS diferencia_mpagodeservicios,
    (t1.cpagomiscuentas - t2.cpagomiscuentas) AS diferencia_cpagomiscuentas,
    (t1.mpagomiscuentas - t2.mpagomiscuentas) AS diferencia_mpagomiscuentas,
    (t1.ccajeros_propios_descuentos - t2.ccajeros_propios_descuentos) AS diferencia_ccajeros_propios_descuentos,
    (t1.mcajeros_propios_descuentos - t2.mcajeros_propios_descuentos) AS diferencia_mcajeros_propios_descuentos,
    (t1.ctarjeta_visa_descuentos - t2.ctarjeta_visa_descuentos) AS diferencia_ctarjeta_visa_descuentos,
    (t1.mtarjeta_visa_descuentos - t2.mtarjeta_visa_descuentos) AS diferencia_mtarjeta_visa_descuentos,
    (t1.ctarjeta_master_descuentos - t2.ctarjeta_master_descuentos) AS diferencia_ctarjeta_master_descuentos,
    (t1.mtarjeta_master_descuentos - t2.mtarjeta_master_descuentos) AS diferencia_mtarjeta_master_descuentos,
    (t1.ccomisiones_mantenimiento - t2.ccomisiones_mantenimiento) AS diferencia_ccomisiones_mantenimiento,
    (t1.mcomisiones_mantenimiento - t2.mcomisiones_mantenimiento) AS diferencia_mcomisiones_mantenimiento,
    (t1.ccomisiones_otras - t2.ccomisiones_otras) AS diferencia_ccomisiones_otras,
    (t1.mcomisiones_otras - t2.mcomisiones_otras) AS diferencia_mcomisiones_otras,
    (t1.cforex - t2.cforex) AS diferencia_cforex,
    (t1.cforex_buy - t2.cforex_buy) AS diferencia_cforex_buy,
    (t1.mforex_buy - t2.mforex_buy) AS diferencia_mforex_buy,
    (t1.cforex_sell - t2.cforex_sell) AS diferencia_cforex_sell,
    (t1.mforex_sell - t2.mforex_sell) AS diferencia_mforex_sell,
    (t1.ctransferencias_recibidas - t2.ctransferencias_recibidas) AS diferencia_ctransferencias_recibidas,
    (t1.mtransferencias_recibidas - t2.mtransferencias_recibidas) AS diferencia_mtransferencias_recibidas,
    (t1.ctransferencias_emitidas - t2.ctransferencias_emitidas) AS diferencia_ctransferencias_emitidas,
    (t1.mtransferencias_emitidas - t2.mtransferencias_emitidas) AS diferencia_mtransferencias_emitidas,
    (t1.cextraccion_autoservicio - t2.cextraccion_autoservicio) AS diferencia_cextraccion_autoservicio,
    (t1.mextraccion_autoservicio - t2.mextraccion_autoservicio) AS diferencia_mextraccion_autoservicio,
    (t1.ccheques_depositados - t2.ccheques_depositados) AS diferencia_ccheques_depositados,
    (t1.mcheques_depositados - t2.mcheques_depositados) AS diferencia_mcheques_depositados,
    (t1.ccheques_emitidos - t2.ccheques_emitidos) AS diferencia_ccheques_emitidos,
    (t1.mcheques_emitidos - t2.mcheques_emitidos) AS diferencia_mcheques_emitidos,
    (t1.ccheques_depositados_rechazados - t2.ccheques_depositados_rechazados) AS diferencia_ccheques_depositados_rechazados,
    (t1.mcheques_depositados_rechazados - t2.mcheques_depositados_rechazados) AS diferencia_mcheques_depositados_rechazados,
    (t1.ccheques_emitidos_rechazados - t2.ccheques_emitidos_rechazados) AS diferencia_ccheques_emitidos_rechazados,
    (t1.mcheques_emitidos_rechazados - t2.mcheques_emitidos_rechazados) AS diferencia_mcheques_emitidos_rechazados,
    (t1.tcallcenter - t2.tcallcenter) AS diferencia_tcallcenter,
    (t1.ccallcenter_transacciones - t2.ccallcenter_transacciones) AS diferencia_ccallcenter_transacciones,
    (t1.thomebanking - t2.thomebanking) AS diferencia_thomebanking,
    (t1.chomebanking_transacciones - t2.chomebanking_transacciones) AS diferencia_chomebanking_transacciones,
    (t1.ccajas_transacciones - t2.ccajas_transacciones) AS diferencia_ccajas_transacciones,
    (t1.ccajas_consultas - t2.ccajas_consultas) AS diferencia_ccajas_consultas,
    (t1.ccajas_depositos - t2.ccajas_depositos) AS diferencia_ccajas_depositos,
    (t1.ccajas_extracciones - t2.ccajas_extracciones) AS diferencia_ccajas_extracciones,
    (t1.ccajas_otras - t2.ccajas_otras) AS diferencia_ccajas_otras,
    (t1.catm_trx - t2.catm_trx) AS diferencia_catm_trx,
    (t1.matm - t2.matm) AS diferencia_matm,
    (t1.catm_trx_other - t2.catm_trx_other) AS diferencia_catm_trx_other,
    (t1.matm_other - t2.matm_other) AS diferencia_matm_other,
    (t1.ctrx_quarter - t2.ctrx_quarter) AS diferencia_ctrx_quarter,
    (t1.tmobile_app - t2.tmobile_app) AS diferencia_tmobile_app,
    (t1.cmobile_app_trx - t2.cmobile_app_trx) AS diferencia_cmobile_app_trx,
    (t1.Master_delinquency - t2.Master_delinquency) AS diferencia_Master_delinquency,
    (t1.Master_mfinanciacion_limite - t2.Master_mfinanciacion_limite) AS diferencia_Master_mfinanciacion_limite,
    (t1.Master_msaldototal - t2.Master_msaldototal) AS diferencia_Master_msaldototal,
    (t1.Master_msaldopesos - t2.Master_msaldopesos) AS diferencia_Master_msaldopesos,
    (t1.Master_msaldodolares - t2.Master_msaldodolares) AS diferencia_Master_msaldodolares,
    (t1.Master_mconsumospesos - t2.Master_mconsumospesos) AS diferencia_Master_mconsumospesos,
    (t1.Master_mconsumosdolares - t2.Master_mconsumosdolares) AS diferencia_Master_mconsumosdolares,
    (t1.Master_mlimitecompra - t2.Master_mlimitecompra) AS diferencia_Master_mlimitecompra,
    (t1.Master_madelantopesos - t2.Master_madelantopesos) AS diferencia_Master_madelantopesos,
    (t1.Master_madelantodolares - t2.Master_madelantodolares) AS diferencia_Master_madelantodolares,
    (t1.Master_mpagado - t2.Master_mpagado) AS diferencia_Master_mpagado,
    (t1.Master_mpagospesos - t2.Master_mpagospesos) AS diferencia_Master_mpagospesos,
    (t1.Master_mpagosdolares - t2.Master_mpagosdolares) AS diferencia_Master_mpagosdolares,
    (t1.Master_mconsumototal - t2.Master_mconsumototal) AS diferencia_Master_mconsumototal,
    (t1.Master_cconsumos - t2.Master_cconsumos) AS diferencia_Master_cconsumos,
    (t1.Master_cadelantosefectivo - t2.Master_cadelantosefectivo) AS diferencia_Master_cadelantosefectivo,
    (t1.Master_mpagominimo - t2.Master_mpagominimo) AS diferencia_Master_mpagominimo,
    (t1.Visa_delinquency - t2.Visa_delinquency) AS diferencia_Visa_delinquency,
    (t1.Visa_mfinanciacion_limite - t2.Visa_mfinanciacion_limite) AS diferencia_Visa_mfinanciacion_limite,
    (t1.Visa_msaldototal - t2.Visa_msaldototal) AS diferencia_Visa_msaldototal,
    (t1.Visa_msaldopesos - t2.Visa_msaldopesos) AS diferencia_Visa_msaldopesos,
    (t1.Visa_msaldodolares - t2.Visa_msaldodolares) AS diferencia_Visa_msaldodolares,
    (t1.Visa_mconsumospesos - t2.Visa_mconsumospesos) AS diferencia_Visa_mconsumospesos,
    (t1.Visa_mconsumosdolares - t2.Visa_mconsumosdolares) AS diferencia_Visa_mconsumosdolares,
    (t1.Visa_mlimitecompra - t2.Visa_mlimitecompra) AS diferencia_Visa_mlimitecompra,
    (t1.Visa_madelantopesos - t2.Visa_madelantopesos) AS diferencia_Visa_madelantopesos,
    (t1.Visa_madelantodolares - t2.Visa_madelantodolares) AS diferencia_Visa_madelantodolares,
    (t1.Visa_mpagado - t2.Visa_mpagado) AS diferencia_Visa_mpagado,
    (t1.Visa_mpagospesos - t2.Visa_mpagospesos) AS diferencia_Visa_mpagospesos,
    (t1.Visa_mpagosdolares - t2.Visa_mpagosdolares) AS diferencia_Visa_mpagosdolares,
    (t1.Visa_mconsumototal - t2.Visa_mconsumototal) AS diferencia_Visa_mconsumototal,
    (t1.Visa_cconsumos - t2.Visa_cconsumos) AS diferencia_Visa_cconsumos,
    (t1.Visa_cadelantosefectivo - t2.Visa_cadelantosefectivo) AS diferencia_Visa_cadelantosefectivo,
    (t1.Visa_mpagominimo - t2.Visa_mpagominimo) AS diferencia_Visa_mpagominimo
    FROM bajas AS t1
    JOIN bajas AS t2 ON t1.numero_de_cliente = t2.numero_de_cliente 
    WHERE t1.clase_ternaria = 'BAJA+2' and t2.clase_ternaria = 'BAJA+1';

Empty DataFrame
Columns: [Success]
Index: []

In [27]:
%%sql 
select * from perfilbaja

,numero_de_cliente,diferencia_active_quarter,diferencia_cliente_vip,diferencia_internet,diferencia_cliente_edad,diferencia_cliente_antiguedad,diferencia_mrentabilidad,diferencia_mrentabilidad_annual,diferencia_mcomisiones,diferencia_mactivos_margen,...,diferencia_Visa_mlimitecompra,diferencia_Visa_madelantopesos,diferencia_Visa_madelantodolares,diferencia_Visa_mpagado,diferencia_Visa_mpagospesos,diferencia_Visa_mpagosdolares,diferencia_Visa_mconsumototal,diferencia_Visa_cconsumos,diferencia_Visa_cadelantosefectivo,diferencia_Visa_mpagominimo
0,989388730,0,0,0,0,-1,-1580.74,-1965.26,-1589.84,22.83,...,0.0,0.0,0.0,0.0,-372.94,0.0,-602.92,0,0,-105.57
1,989470994,0,0,0,0,-1,-1185.67,-2299.46,-892.33,-69.74,...,0.0,0.0,0.0,0.0,2710.80,0.0,7959.49,4,0,410.55
2,989989133,-1,0,0,0,-1,-233.24,320.31,-367.16,198.36,...,0.0,NaN,NaN,0.0,NaN,NaN,NaN,<NA>,<NA>,-750.72
3,991046429,0,0,0,0,-1,-629.98,-695.30,-539.97,-76.53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN
4,992159012,0,0,0,0,-1,-499.20,1419.80,-453.83,-123.85,...,0.0,0.0,0.0,0.0,1316.30,0.0,343.18,1,0,23.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3900,998205972,0,0,0,0,-1,959.21,990.04,83.96,759.89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN
3901,1000241511,1,0,-1,0,-1,-69.31,-146.83,0.00,-59.09,...,0.0,NaN,NaN,0.0,NaN,NaN,NaN,<NA>,<NA>,0.00
3902,1000665150,0,0,0,0,-1,3.03,1918.90,0.00,0.81,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN
3903,1000849728,-1,0,0,-1,-1,1862.15,-4760.65,1592.20,238.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN
3904,1002534848,0,0,0,0,-1,49.45,-433.51,0.00,202.59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN

In [28]:
%sql COPY perfilbaja TO '/home/augusto/Desktop/dmeyf2025/Data/perfilado.csv' (FORMAT CSV, HEADER)

Empty DataFrame
Columns: [Success]
Index: []